AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: sportcenter-booking lambdas
Globals:
  Function: 
    Timeout: 5
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Develop
  ReserveRegistry:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./reservationRegistry
      Handler: reservation-registry
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3Bucket: default-bucket
          secretKey: 32byte-hex
      Events:
        Api:
          Type: Api
          Properties:
            Path: '/api/registry'
            Method: post
            RestApiId: ApiGatewayApi
  FetchRegistry:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./fetchRegistry
      Handler: fetch-registry
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3Bucket: default-bucket
          secretKey: 32byte-hex
      Events:
        Api:
          Type: Api
          Properties:
            Path: '/api/registry'
            Method: get
            RestApiId: ApiGatewayApi
  DailyExecCheck:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dailyExecCheck
      Handler: daily-check
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3Bucket: default-bucket
          SecretKeyName: secret-manager-key-name